### ISSUE TITLE
Centos package manager issue (formula rerun)

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/etcd-formula#26]
Noting some weird package manager issue on Centos 7 on formula rerun.
```
----------
          ID: etcd-docker-python2-docker-package
    Function: pkg.installed
        Name: python2-docker
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit run-6142.scope.
                    Loaded plugins: fastestmirror, versionlock
                    Loading mirror speeds from cached hostfile
                     * base: mirror.strencom.net
                     * epel: ftp.nluug.nl
                     * extras: mirror.strencom.net
                     * updates: mirror.strencom.net
                    Resolving Dependencies
                    --> Running transaction check
                    ---> Package python2-docker.noarch 0:2.4.2-1.2.el7 will be installed
                    --> Processing Dependency: python2-six >= 1.4.0 for package: python2-docker-2.4.2-1.2.el7.noarch
                    --> Processing Dependency: python-websocket-client >= 0.32.0 for package: python2-docker-2.4.2-1.2.el7.noarch
                    --> Processing Dependency: python2-requests for package: python2-docker-2.4.2-1.2.el7.noarch
                    --> Processing Dependency: python-docker-pycreds for package: python2-docker-2.4.2-1.2.el7.noarch
                    --> Running transaction check
                    ---> Package python-requests.noarch 0:2.6.0-1.el7_1 will be obsoleted
                    ---> Package python-six.noarch 0:1.9.0-2.el7 will be obsoleted
                    ---> Package python-websocket-client.noarch 0:0.34.0-3.el7 will be installed
                    ---> Package python2-docker-pycreds.noarch 0:0.2.1-4.el7 will be installed
                    ---> Package python2-requests.noarch 0:2.14.2-1.el7 will be obsoleting
                    --> Processing Dependency: python2-urllib3 = 1.21.1 for package: python2-requests-2.14.2-1.el7.noarch
                    ---> Package python2-six.noarch 0:1.10.0-9.el7 will be obsoleting
                    --> Running transaction check
                    ---> Package python-urllib3.noarch 0:1.10.2-5.el7 will be obsoleted
                    ---> Package python2-urllib3.noarch 0:1.21.1-1.el7 will be obsoleting
                    --> Processing Dependency: python-pysocks for package: python2-urllib3-1.21.1-1.el7.noarch
                    --> Running transaction check
                    ---> Package python2-pysocks.noarch 0:1.6.8-5.el7 will be installed
                    --> Finished Dependency Resolution
                    
                    Dependencies Resolved
                    
                    ================================================================================
                     Package                   Arch     Version            Repository          Size
                    ================================================================================
                    Installing:
                     python2-docker            noarch   2.4.2-1.2.el7      openstack-queens   168 k
                     python2-requests          noarch   2.14.2-1.el7       openstack-queens   116 k
                         replacing  python-requests.noarch 2.6.0-1.el7_1
                     python2-six               noarch   1.10.0-9.el7       openstack-queens    31 k
                         replacing  python-six.noarch 1.9.0-2.el7
                     python2-urllib3           noarch   1.21.1-1.el7       openstack-queens   173 k
                         replacing  python-urllib3.noarch 1.10.2-5.el7
                    Installing for dependencies:
                     python-websocket-client   noarch   0.34.0-3.el7       openstack-queens    57 k
                     python2-docker-pycreds    noarch   0.2.1-4.el7        openstack-queens    15 k
                     python2-pysocks           noarch   1.6.8-5.el7        epel                30 k
                    
                    Transaction Summary
                    ================================================================================
                    Install  4 Packages (+3 Dependent packages)
                    
                    Total download size: 589 k
                    Downloading packages:
                    --------------------------------------------------------------------------------
                    Total                                              414 kB/s | 589 kB  00:01     
                    Running transaction check
                    Running transaction test
                    Transaction test succeeded
                    Running transaction
                      Installing : python2-six-1.10.0-9.el7.noarch                             1/10 
                      Installing : python-websocket-client-0.34.0-3.el7.noarch                 2/10 
                      Installing : python2-docker-pycreds-0.2.1-4.el7.noarch                   3/10 
                      Installing : python2-pysocks-1.6.8-5.el7.noarch                          4/10 
                      Installing : python2-urllib3-1.21.1-1.el7.noarch                         5/10Error unpacking rpm package python2-urllib3-1.21.1-1.el7.noarch
                     
                    error: unpacking of archive failed on file /usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname: cpio: rename
                      Installing : python2-requests-2.14.2-1.el7.noarch                        6/10 
                    error: python2-urllib3-1.21.1-1.el7.noarch: install failed
                      Installing : python2-docker-2.4.2-1.2.el7.noarch                         7/10 
                      Erasing    : python-requests-2.6.0-1.el7_1.noarch                        8/10 
                    warning: file /usr/lib/python2.7/site-packages/requests-2.6.0-py2.7.egg-info: remove failed: No such file or directory
                      Erasing    : python-six-1.9.0-2.el7.noarch                               9/10 
                    error: python-urllib3-1.10.2-5.el7.noarch: erase skipped
                    warning: file /usr/lib/python2.7/site-packages/six-1.9.0-py2.7.egg-info/top_level.txt: remove failed: No such file or directory
                    warning: file /usr/lib/python2.7/site-packages/six-1.9.0-py2.7.egg-info/dependency_links.txt: remove failed: No such file or directory
                    warning: file /usr/lib/python2.7/site-packages/six-1.9.0-py2.7.egg-info/SOURCES.txt: remove failed: No such file or directory
                    warning: file /usr/lib/python2.7/site-packages/six-1.9.0-py2.7.egg-info/PKG-INFO: remove failed: No such file or directory
                    warning: file /usr/lib/python2.7/site-packages/six-1.9.0-py2.7.egg-info: remove failed: No such file or directory
                      Verifying  : python2-pysocks-1.6.8-5.el7.noarch                          1/10 
                      Verifying  : python-websocket-client-0.34.0-3.el7.noarch                 2/10 
                      Verifying  : python2-requests-2.14.2-1.el7.noarch                        3/10 
                      Verifying  : python2-six-1.10.0-9.el7.noarch                             4/10 
                      Verifying  : python2-docker-2.4.2-1.2.el7.noarch                         5/10 
                      Verifying  : python2-docker-pycreds-0.2.1-4.el7.noarch                   6/10python-urllib3-1.10.2-5.el7.noarch was supposed to be removed but is not!
                     
                      Verifying  : python-urllib3-1.10.2-5.el7.noarch                          7/10 
                      Verifying  : python2-urllib3-1.21.1-1.el7.noarch                         8/10 
                      Verifying  : python-requests-2.6.0-1.el7_1.noarch                        9/10 
                      Verifying  : python-six-1.9.0-2.el7.noarch                              10/10 
                    
                    Installed:
                      python2-docker.noarch 0:2.4.2-1.2.el7  python2-requests.noarch 0:2.14.2-1.el7 
                      python2-six.noarch 0:1.10.0-9.el7     
                    
                    Dependency Installed:
                      python-websocket-client.noarch 0:0.34.0-3.el7                                 
                      python2-docker-pycreds.noarch 0:0.2.1-4.el7                                   
                      python2-pysocks.noarch 0:1.6.8-5.el7                                          
                    
                    Replaced:
                      python-requests.noarch 0:2.6.0-1.el7_1     python-six.noarch 0:1.9.0-2.el7    
                    
                    Failed:
                      python-urllib3.noarch 0:1.10.2-5.el7   python2-urllib3.noarch 0:1.21.1-1.el7  
                    
                    Complete!
     Started: 21:09:13.903760
    Duration: 9201.153 ms
     Changes:   
              ----------
              python-requests:
                  ----------
                  new:
                  old:
                      2.6.0-1.el7_1
              python-six:
                  ----------
                  new:
                  old:
                      1.9.0-2.el7
              python-websocket-client:
                  ----------
                  new:
                      0.34.0-3.el7
                  old:
              python2-docker:
                  ----------
                  new:
                      2.4.2-1.2.el7
                  old:
              python2-docker-pycreds:
                  ----------
                  new:
                      0.2.1-4.el7
                  old:
              python2-pysocks:
                  ----------
                  new:
                      1.6.8-5.el7
                  old:
              python2-requests:
                  ----------
                  new:
                      2.14.2-1.el7
                  old:
              python2-six:
                  ----------
                  new:
                      1.10.0-9.el7
                  old:
----------
          ID: etcd-docker-python-pip-install
    Function: pip.installed
        Name: docker
      Result: True
     Comment: Python package docker was already installed
              All specified packages are already installed
     Started: 21:09:24.055855
    Duration: 579.527 ms
     Changes:   
----------
          ID: etcd-ensure-docker-service
    Function: service.running
        Name: docker
      Result: True
     Comment: The service docker is already running
     Started: 21:09:24.637415
    Duration: 30.214 ms
     Changes:   
----------
          ID: run-etcd-dockerized-service
    Function: docker_container.running
      Result: False
     Comment: One or more requisite failed: etcd.docker.running.etcd-docker-python2-docker-package
     Started: 21:09:24.673146
    Duration: 0.032 ms
    
```

**Comment by noelmcloughlin** [comment]
Causes this problem on `run-etcd-dockerized-service` ...
```
          ID: run-etcd-dockerized-service
    Function: docker_container.running
      Result: False
     Comment: Created container 'run-etcd-dockerized-service'. Failed to start container 'run-etcd-dockerized-service': 'Error 500: driver failed programming external connectivity on endpoint run-etcd-dockerized-service (20d6a8ac8c4ccb30f1af9b593e83671ced428132569ecc80cdd8debcab5cdca1):  (iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.4 --dport 2380 -j ACCEPT: iptables: No chain/target/match by that name.
               (exit status 1))'.
     Started: 22:53:03.929971
    Duration: 11597.317 ms
     Changes:   
              ----------
              container_id:
                  ----------
                  added:
                      c485179b40d24f7f3e98fb94583db957d11022cf90685520be33ae562fb00c29
              image:
                  ----------
                  Layers:
                      ----------
                      Already_Pulled:
                          - ff3a5c916c92
                      Pulled:
                          - 96bbfc0d3fe8
                          - a66f6545e80b
                          - 99e523d78742
                          - f7d4ae8b57f8
                          - 07db19df0d1f
                  Status:
                      Downloaded newer image for gcr.io/etcd-development/etcd:v3.2.24
                  Time_Elapsed:
                      2.31009507179
                  retcode:
                      0
```
