### ISSUE TITLE
Cannot bind etcd on a specific IP

### ISSUE THREAD

**Issue by Morsicus** [saltstack-formulas/etcd-formula#8]
Hello :)

## Summary
Etcd cannot be bind to a specific IP. Default value (127.0.0.1) cannot be overloaded by my pillars.
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      19470/etcd
tcp        0      0 127.0.0.1:2380          0.0.0.0:*               LISTEN      19470/etcd
```

## Details
Running on ubuntu 16.04

## Pillars examples
(Copy of pillar.example)

```yaml
etcd:
  lookup:
    version: 3.2.18

  service:
    name: etcd0
    data_dir: /var/lib/etcd/etcd0
    initial_cluster: etcd0=https://0.0.0.0:2380
    initial_cluster_state: new
    initial_cluster_token: etcd-cluster-1
    initial_advertise_peer_urls: https://0.0.0.0:2380
    listen_peer_urls: https://0.0.0.0:2380
    listen_client_urls: https://0.0.0.0:2379
    advertise_client_urls: https://0.0.0.0:2379
    auto_tls: '"false"'
    peer_auto_tls: '"false"'
    proxy: OFF
```

## Expected behaviour
ETCD should be listening to *:2379 and *2380

## Possible fix
Issue seems to be related to this [line](https://github.com/saltstack-formulas/etcd-formula/blob/master/etcd/files/systemd.service.jinja#L10). etcd.lookup doesn't contain etcd listening configuration. 

Thanks :)
